export const MINUTES_LIST = [
  { textAr: '00', textEn: '00', value: '00', isSelected: false },
  { textAr: '01', textEn: '01', value: '01', isSelected: false },
  { textAr: '02', textEn: '02', value: '02', isSelected: false },
  { textAr: '03', textEn: '03', value: '03', isSelected: false },
  { textAr: '04', textEn: '04', value: '04', isSelected: false },
  { textAr: '05', textEn: '05', value: '05', isSelected: false },
  { textAr: '06', textEn: '06', value: '06', isSelected: false },
  { textAr: '07', textEn: '07', value: '07', isSelected: false },
  { textAr: '08', textEn: '08', value: '08', isSelected: false },
  { textAr: '09', textEn: '09', value: '09', isSelected: false },
  { textAr: '10', textEn: '10', value: '10', isSelected: false },
  { textAr: '11', textEn: '11', value: '11', isSelected: false },
  { textAr: '12', textEn: '12', value: '12', isSelected: false },
  { textAr: '13', textEn: '13', value: '13', isSelected: false },
  { textAr: '14', textEn: '14', value: '14', isSelected: false },
  { textAr: '15', textEn: '15', value: '15', isSelected: false },
  { textAr: '16', textEn: '16', value: '16', isSelected: false },
  { textAr: '17', textEn: '17', value: '17', isSelected: false },
  { textAr: '18', textEn: '18', value: '18', isSelected: false },
  { textAr: '19', textEn: '19', value: '19', isSelected: false },
  { textAr: '20', textEn: '20', value: '20', isSelected: false },
  { textAr: '21', textEn: '21', value: '21', isSelected: false },
  { textAr: '22', textEn: '22', value: '22', isSelected: false },
  { textAr: '23', textEn: '23', value: '23', isSelected: false },
  { textAr: '24', textEn: '24', value: '24', isSelected: false },
  { textAr: '25', textEn: '25', value: '25', isSelected: false },
  { textAr: '26', textEn: '26', value: '26', isSelected: false },
  { textAr: '27', textEn: '27', value: '27', isSelected: false },
  { textAr: '28', textEn: '28', value: '28', isSelected: false },
  { textAr: '29', textEn: '29', value: '29', isSelected: false },
  { textAr: '30', textEn: '30', value: '30', isSelected: false },
  { textAr: '31', textEn: '31', value: '31', isSelected: false },
  { textAr: '32', textEn: '32', value: '32', isSelected: false },
  { textAr: '33', textEn: '33', value: '33', isSelected: false },
  { textAr: '34', textEn: '34', value: '34', isSelected: false },
  { textAr: '35', textEn: '35', value: '35', isSelected: false },
  { textAr: '36', textEn: '36', value: '36', isSelected: false },
  { textAr: '37', textEn: '37', value: '37', isSelected: false },
  { textAr: '38', textEn: '38', value: '38', isSelected: false },
  { textAr: '39', textEn: '39', value: '39', isSelected: false },
  { textAr: '40', textEn: '40', value: '40', isSelected: false },
  { textAr: '41', textEn: '41', value: '41', isSelected: false },
  { textAr: '42', textEn: '42', value: '42', isSelected: false },
  { textAr: '43', textEn: '43', value: '43', isSelected: false },
  { textAr: '44', textEn: '44', value: '44', isSelected: false },
  { textAr: '45', textEn: '45', value: '45', isSelected: false },
  { textAr: '46', textEn: '46', value: '46', isSelected: false },
  { textAr: '47', textEn: '47', value: '47', isSelected: false },
  { textAr: '48', textEn: '48', value: '48', isSelected: false },
  { textAr: '49', textEn: '49', value: '49', isSelected: false },
  { textAr: '50', textEn: '50', value: '50', isSelected: false },
  { textAr: '51', textEn: '51', value: '51', isSelected: false },
  { textAr: '52', textEn: '52', value: '52', isSelected: false },
  { textAr: '53', textEn: '53', value: '53', isSelected: false },
  { textAr: '54', textEn: '54', value: '54', isSelected: false },
  { textAr: '55', textEn: '55', value: '55', isSelected: false },
  { textAr: '56', textEn: '56', value: '56', isSelected: false },
  { textAr: '57', textEn: '57', value: '57', isSelected: false },
  { textAr: '58', textEn: '58', value: '58', isSelected: false },
  { textAr: '59', textEn: '59', value: '59', isSelected: false },
] as const;

export const HOURS_LIST = [
  { textAr: '01', textEn: '01', value: '1', isSelected: false },
  { textAr: '02', textEn: '02', value: '2', isSelected: false },
  { textAr: '03', textEn: '03', value: '3', isSelected: false },
  { textAr: '04', textEn: '04', value: '4', isSelected: false },
  { textAr: '05', textEn: '05', value: '5', isSelected: false },
  { textAr: '06', textEn: '06', value: '6', isSelected: false },
  { textAr: '07', textEn: '07', value: '7', isSelected: false },
  { textAr: '08', textEn: '08', value: '8', isSelected: false },
  { textAr: '09', textEn: '09', value: '9', isSelected: false },
  { textAr: '10', textEn: '10', value: '10', isSelected: false },
  { textAr: '11', textEn: '11', value: '11', isSelected: false },
  { textAr: '12', textEn: '12', value: '12', isSelected: false },
] as const;

export const PERIODS_LIST = [
  { textAr: 'صباحا', textEn: 'AM', value: 'AM', isSelected: false },
  { textAr: 'مساء', textEn: 'PM', value: 'PM', isSelected: false },
] as const;
